//
// ColorExternalProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ColorExternalProvider: Sendable, Codable, ParameterConvertible, Hashable {
    public var extDescrs: [[String?]?]?
    public var extIds: [Int?]?

    public init(extDescrs: [[String?]?]?, extIds: [Int?]?) {
        self.extDescrs = extDescrs
        self.extIds = extIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case extDescrs = "ext_descrs"
        case extIds = "ext_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(extDescrs, forKey: .extDescrs)
        try container.encode(extIds, forKey: .extIds)
    }
}
