//
// Element.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Element: Sendable, Codable, ParameterConvertible, Hashable {
    public var part: Part?
    public var color: Color?
    public var elementId: String?
    public var designId: String?
    public var elementImgUrl: String?
    public var partImgUrl: String?

    public init(part: Part? = nil, color: Color? = nil, elementId: String? = nil, designId: String? = nil, elementImgUrl: String? = nil, partImgUrl: String? = nil) {
        self.part = part
        self.color = color
        self.elementId = elementId
        self.designId = designId
        self.elementImgUrl = elementImgUrl
        self.partImgUrl = partImgUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case part
        case color
        case elementId = "element_id"
        case designId = "design_id"
        case elementImgUrl = "element_img_url"
        case partImgUrl = "part_img_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(part, forKey: .part)
        try container.encode(color, forKey: .color)
        try container.encode(elementId, forKey: .elementId)
        try container.encode(designId, forKey: .designId)
    try container.encodeIfPresent(elementImgUrl, forKey: .elementImgUrl)
    try container.encodeIfPresent(partImgUrl, forKey: .partImgUrl)
    }
}
