//
// Moc.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Moc: Sendable, Codable, ParameterConvertible, Hashable {

    public var setNum: String
    public var name: String
    public var year: Int?
    public var themeId: Int?
    public var numParts: Int
    public var mocImgUrl: String
    public var mocUrl: String
    public var designerName: String
    public var designerUrl: String

    public init(setNum: String, name: String, year: Int? = nil, themeId: Int? = nil, numParts: Int, mocImgUrl: String, mocUrl: String, designerName: String, designerUrl: String) {
        self.setNum = setNum
        self.name = name
        self.year = year
        self.themeId = themeId
        self.numParts = numParts
        self.mocImgUrl = mocImgUrl
        self.mocUrl = mocUrl
        self.designerName = designerName
        self.designerUrl = designerUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case setNum = "set_num"
        case name
        case year
        case themeId = "theme_id"
        case numParts = "num_parts"
        case mocImgUrl = "moc_img_url"
        case mocUrl = "moc_url"
        case designerName = "designer_name"
        case designerUrl = "designer_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(setNum, forKey: .setNum)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(themeId, forKey: .themeId)
        try container.encode(numParts, forKey: .numParts)
        try container.encode(mocImgUrl, forKey: .mocImgUrl)
        try container.encode(mocUrl, forKey: .mocUrl)
        try container.encode(designerName, forKey: .designerName)
        try container.encode(designerUrl, forKey: .designerUrl)
    }
}

