//
// PartExternalIds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PartExternalIds: Sendable, Codable, ParameterConvertible, Hashable {

    public var brickLink: [String]
    public var brickOwl: [String]
    public var brickset: [String]?
    public var lDraw: [String]?
    public var LEGO: [String]?

    public init(brickLink: [String], brickOwl: [String], brickset: [String]? = nil, lDraw: [String]? = nil, LEGO: [String]? = nil) {
        self.brickLink = brickLink
        self.brickOwl = brickOwl
        self.brickset = brickset
        self.lDraw = lDraw
        self.LEGO = LEGO
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brickLink = "BrickLink"
        case brickOwl = "BrickOwl"
        case brickset = "Brickset"
        case lDraw = "LDraw"
        case LEGO
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brickLink, forKey: .brickLink)
        try container.encode(brickOwl, forKey: .brickOwl)
        try container.encodeIfPresent(brickset, forKey: .brickset)
        try container.encodeIfPresent(lDraw, forKey: .lDraw)
        try container.encodeIfPresent(LEGO, forKey: .LEGO)
    }
}

