//
// PartCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PartCategory: Sendable, Codable, ParameterConvertible, Hashable {
    public var id: Int?
    public var name: String?
    public var partCount: Int?

    public init(id: Int? = nil, name: String? = nil, partCount: Int? = nil) {
        self.id = id
        self.name = name
        self.partCount = partCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case partCount = "part_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(partCount, forKey: .partCount)
    }
}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PartCategory: Identifiable {}
