//
// SetBase.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetBase: Sendable, Codable, ParameterConvertible, Hashable {
    public var setNum: String
    public var name: String
    public var year: Int?
    public var themeId: Int?
    public var numParts: Int

    public init(setNum: String, name: String, year: Int? = nil, themeId: Int? = nil, numParts: Int) {
        self.setNum = setNum
        self.name = name
        self.year = year
        self.themeId = themeId
        self.numParts = numParts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case setNum = "set_num"
        case name
        case year
        case themeId = "theme_id"
        case numParts = "num_parts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(setNum, forKey: .setNum)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(themeId, forKey: .themeId)
        try container.encode(numParts, forKey: .numParts)
    }
}
