//
// ColorExternalIds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ColorExternalIds: Sendable, Codable, ParameterConvertible, Hashable {
    public var brickLink: ColorExternalProvider?
    public var brickOwl: ColorExternalProvider?
    public var lDraw: ColorExternalProvider?
    public var LEGO: ColorExternalProvider?
    public var peeron: ColorExternalProvider?

    public init(
        brickLink: ColorExternalProvider?, brickOwl: ColorExternalProvider?,
        lDraw: ColorExternalProvider?, LEGO: ColorExternalProvider?, peeron: ColorExternalProvider?
    ) {
        self.brickLink = brickLink
        self.brickOwl = brickOwl
        self.lDraw = lDraw
        self.LEGO = LEGO
        self.peeron = peeron
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brickLink = "BrickLink"
        case brickOwl = "BrickOwl"
        case lDraw = "LDraw"
        case LEGO
        case peeron = "Peeron"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brickLink, forKey: .brickLink)
        try container.encode(brickOwl, forKey: .brickOwl)
        try container.encode(lDraw, forKey: .lDraw)
        try container.encode(LEGO, forKey: .LEGO)
        try container.encode(peeron, forKey: .peeron)
    }
}
