//
// SetPartMinifig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetPartMinifig: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int
    public var setNum: String
    public var setName: String?
    public var quantity: Int
    public var setImgUrl: String?

    public init(id: Int, setNum: String, setName: String? = nil, quantity: Int, setImgUrl: String? = nil) {
        self.id = id
        self.setNum = setNum
        self.setName = setName
        self.quantity = quantity
        self.setImgUrl = setImgUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case setNum = "set_num"
        case setName = "set_name"
        case quantity
        case setImgUrl = "set_img_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(setNum, forKey: .setNum)
        try container.encodeIfPresent(setName, forKey: .setName)
        try container.encode(quantity, forKey: .quantity)
        try container.encodeIfPresent(setImgUrl, forKey: .setImgUrl)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SetPartMinifig: Identifiable {}
