//
// Theme.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Theme: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int
    public var parentId: Int?
    public var name: String

    public init(id: Int, parentId: Int? = nil, name: String) {
        self.id = id
        self.parentId = parentId
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case parentId = "parent_id"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(name, forKey: .name)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Theme: Identifiable {}
